# Generated by Django 4.2.15 on 2024-08-14 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=120)),
                ('recurring', models.BooleanField(default=False)),
                ('freq', models.IntegerField(choices=[(0, 'Not recurring'), (1, 'Monthly'), (3, 'Quarterly'), (12, 'Annually'), (-1, 'Other')], default=0)),
                ('amount', models.FloatField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=120)),
                ('category', models.IntegerField(blank=True, choices=[(0, 'Rent'), (1, 'Mortgage Loan'), (2, 'Utilities'), (3, 'Food'), (4, 'Transportation'), (5, 'Car Insurance'), (6, 'Car Repairs'), (7, 'Fuel'), (8, 'Entertainment'), (9, 'Furnishings'), (10, 'Home Insurnace'), (11, 'Life Insurnace'), (12, 'Retirement'), (13, 'Savings'), (14, 'Student Loans'), (15, 'Loan'), (16, 'Child Expenses'), (17, 'Mobile phone'), (18, 'Broadband'), (19, 'Other')])),
                ('recurring', models.BooleanField(default=False)),
                ('freq', models.IntegerField(choices=[(0, 'Not recurring'), (1, 'Monthly'), (3, 'Quarterly'), (12, 'Annually'), (-1, 'Other')], default=0)),
                ('amount', models.FloatField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
