# Generated by Django 4.2.15 on 2024-08-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.IntegerField(choices=[(0, 'Rent'), (1, 'Mortgage Loan'), (2, 'Utilities'), (3, 'Food'), (4, 'Transportation'), (5, 'Car Insurance'), (6, 'Car Repairs'), (7, 'Fuel'), (8, 'Entertainment'), (9, 'Furnishings'), (10, 'Home Insurnace'), (11, 'Life Insurnace'), (12, 'Retirement'), (13, 'Savings'), (14, 'Student Loans'), (15, 'Loan'), (16, 'Child Expenses'), (17, 'Mobile phone'), (18, 'Broadband'), (19, 'Other'), (20, 'Blank')], default=20),
        ),
    ]
